# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lvcy's Blog
email: 757104454@qq.com
description: > # this means to ignore newlines until "baseurl:"
  关注美女和程序设计
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lvchenyang.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  lvchenyang

# Build settings
markdown: kramdown
